"""Typed native-command and safe subprocess access to syq."""

from importlib.metadata import version as distribution_version

from ._stream_endpoints import StreamSource, StreamDestination
from ._streams import StreamReader, StreamWriter, AsyncStreamReader, AsyncStreamWriter
from ._defaults import CLIENT_DEFAULT, Timeout
from ._mapping import Mapping, AsyncMapping
from .async_client import AsyncClient, AsyncMapStream
from .managed import PINNED_SYQ_VERSION, SyqInstallError, managed_executable
from .client import Client, MapStream, Result, run, version
from .errors import (
    SyqError,
    SyqInvocationError,
    SyqOperationError,
    SyqOutputError,
    SyqProcessError,
    SyqProtocolError,
)
from .models import (
    AutomationEvent,
    ProtocolMetadata,
    ReceiptSummary,
    CpResult,
    Disposition,
    AttestedHash,
    Hash,
    HashAlgorithm,
    FinalObjectKind,
    FinalObjectState,
    FinalStateEvent,
    ObjectMetadata,
    Endpoint,
    EndpointKind,
    EndpointRole,
    EntryKind,
    ErrorClass,
    ErrorEvent,
    IgnoreFrom,
    MappingEntry,
    MappingStreamResult,
    DestinationMetadata,
    OperationAction,
    ReceiptCode,
    ReceiptStatus,
    OperationResult,
    OperationStatus,
    OsKind,
    PathValue,
    ProgressEvent,
    RelativePath,
    Retryability,
    RmResult,
    RunEvent,
    SelectionResult,
    SelectionStatus,
    RemovalDisposition,
    RemovalResult,
    RemovalTrace,
    TraceEvent,
    TraceReason,
)

_default_client = Client()
cp = _default_client.cp
rm = _default_client.rm
map = _default_client.map
open_reader = _default_client.open_reader
open_writer = _default_client.open_writer

__all__ = [
    "StreamSource", "StreamDestination",
    "StreamReader", "StreamWriter", "AsyncStreamReader", "AsyncStreamWriter",
    "open_reader", "open_writer",
    "CLIENT_DEFAULT",
    "Timeout",
    "PINNED_SYQ_VERSION",
    "AsyncClient",
    "AsyncMapStream",
    "AutomationEvent",
    "ProtocolMetadata",
    "ReceiptSummary",
    "SyqError",
    "Client",
    "CpResult",
    "Disposition",
    "AttestedHash",
    "Hash",
    "HashAlgorithm",
    "FinalObjectKind",
    "FinalObjectState",
    "FinalStateEvent",
    "ObjectMetadata",
    "Endpoint",
    "EndpointKind",
    "EndpointRole",
    "EntryKind",
    "ErrorClass",
    "ErrorEvent",
    "IgnoreFrom",
    "Mapping",
    "AsyncMapping",
    "MapStream",
    "MappingEntry",
    "MappingStreamResult",
    "DestinationMetadata",
    "OperationAction",
    "ReceiptCode",
    "ReceiptStatus",
    "OperationResult",
    "OperationStatus",
    "OsKind",
    "PathValue",
    "ProgressEvent",
    "RelativePath",
    "Result",
    "Retryability",
    "RmResult",
    "RunEvent",
    "SelectionResult",
    "SelectionStatus",
    "RemovalDisposition",
    "RemovalResult",
    "RemovalTrace",
    "SyqInstallError",
    "SyqInvocationError",
    "SyqOperationError",
    "SyqOutputError",
    "SyqProcessError",
    "SyqProtocolError",
    "TraceEvent",
    "TraceReason",
    "cp",
    "managed_executable",
    "map",
    "rm",
    "run",
    "version",
]

__version__ = distribution_version("syq")
