//! Restricted-receiver enrollment primitives.
//!
//! This module deliberately contains no user-facing installer yet.  It keeps
//! the security-sensitive authorized-keys representation and the safe
//! end-to-end SSH route independent from the receiver implementation so an
//! installer cannot get ahead of the receiver's confinement boundary.
//!
//! Callers own the filesystem and private-key boundary that this byte-level
//! foundation intentionally does not implement. Before exposing enrollment,
//! a caller must generate a dedicated Ed25519 private key with a CSPRNG, store
//! it in a trusted private directory with mode 0600, and replace
//! `authorized_keys` atomically without following symlinks while preserving
//! the target account's ownership and StrictModes-compatible permissions.

use anyhow::{bail, Context, Result};
use base64::Engine as _;
use std::path::{Component, Path};

const ENROLLMENT_ID_BYTES: usize = 16;
const ED25519_ALGORITHM: &str = "ssh-ed25519";
const ED25519_KEY_BYTES: usize = 32;
const COMMENT_PREFIX: &str = "syq-enrollment:";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EnrollmentId(String);

impl EnrollmentId {
    pub fn parse(value: &str) -> Result<Self> {
        if value.len() != ENROLLMENT_ID_BYTES * 2
            || !value
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
        {
            bail!(
                "enrollment ID must be {} lowercase hexadecimal characters",
                ENROLLMENT_ID_BYTES * 2
            );
        }
        let bytes = (0..ENROLLMENT_ID_BYTES)
            .map(|index| u8::from_str_radix(&value[index * 2..index * 2 + 2], 16))
            .collect::<std::result::Result<Vec<_>, _>>()
            .expect("lowercase hexadecimal enrollment ID");
        let version = bytes[6] >> 4;
        if bytes[8] & 0xc0 != 0x80 || !(1..=8).contains(&version) {
            bail!("enrollment ID must be an RFC 4122 UUID");
        }
        Ok(Self(value.to_owned()))
    }

    pub fn random() -> Self {
        let mut bytes = crate::crypto::random_bytes(ENROLLMENT_ID_BYTES);
        // RFC 4122 variant, randomly generated (version 4).  The on-wire and
        // authorized_keys spelling stays compact lowercase hexadecimal.
        bytes[6] = (bytes[6] & 0x0f) | 0x40;
        bytes[8] = (bytes[8] & 0x3f) | 0x80;
        let mut value = String::with_capacity(ENROLLMENT_ID_BYTES * 2);
        for byte in bytes {
            use std::fmt::Write as _;
            write!(&mut value, "{byte:02x}").expect("write to String");
        }
        Self(value)
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    fn marker(&self) -> String {
        format!("{COMMENT_PREFIX}{}", self.0)
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TransportPublicKey {
    algorithm: String,
    blob: String,
}

impl TransportPublicKey {
    /// Parse the public half of the dedicated receiver transport key.
    ///
    /// The first enrollment version intentionally accepts only Ed25519.  This
    /// key is generated by syq and is not the user's SSH/YubiKey signing key.
    pub fn parse(line: &str) -> Result<Self> {
        let mut words = line.split_ascii_whitespace();
        let algorithm = words.next().context("transport public key is empty")?;
        let blob = words
            .next()
            .context("transport public key has no key blob")?;
        if algorithm != ED25519_ALGORITHM {
            bail!("receiver transport key must use {ED25519_ALGORITHM}");
        }
        let decoded = base64::engine::general_purpose::STANDARD
            .decode(blob)
            .context("transport public key is not valid base64")?;
        validate_ed25519_blob(&decoded)?;
        Ok(Self {
            algorithm: algorithm.to_owned(),
            blob: blob.to_owned(),
        })
    }
}

fn take_ssh_string<'a>(input: &mut &'a [u8]) -> Result<&'a [u8]> {
    let length_bytes: [u8; 4] = input
        .get(..4)
        .context("truncated SSH string length")?
        .try_into()
        .expect("four-byte slice");
    *input = &input[4..];
    let length = u32::from_be_bytes(length_bytes) as usize;
    let value = input.get(..length).context("truncated SSH string")?;
    *input = &input[length..];
    Ok(value)
}

fn validate_ed25519_blob(mut blob: &[u8]) -> Result<()> {
    if take_ssh_string(&mut blob)? != ED25519_ALGORITHM.as_bytes() {
        bail!("transport public key blob has the wrong algorithm");
    }
    if take_ssh_string(&mut blob)?.len() != ED25519_KEY_BYTES {
        bail!("transport public key has the wrong Ed25519 key length");
    }
    if !blob.is_empty() {
        bail!("transport public key blob has trailing data");
    }
    Ok(())
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AuthorizedKeyEntry {
    id: EnrollmentId,
    key: TransportPublicKey,
    line: String,
}

impl AuthorizedKeyEntry {
    pub fn new(id: EnrollmentId, receiver_path: &Path, key: &TransportPublicKey) -> Result<Self> {
        let receiver = safe_receiver_path(receiver_path)?;
        let command = format!(
            "{receiver} --restricted-receiver --enrollment={}",
            id.as_str()
        );
        let line = format!(
            "restrict,command=\"{command}\" {} {} {}",
            key.algorithm,
            key.blob,
            id.marker()
        );
        Ok(Self {
            id,
            key: key.clone(),
            line,
        })
    }

    pub fn line(&self) -> &str {
        &self.line
    }

    pub fn marker(&self) -> String {
        self.id.marker()
    }
}

fn safe_receiver_path(path: &Path) -> Result<String> {
    if !path.is_absolute() {
        bail!("restricted receiver path must be absolute");
    }
    for component in path.components() {
        match component {
            Component::RootDir | Component::Normal(_) => {}
            _ => bail!("restricted receiver path must not contain . or .. components"),
        }
    }
    let value = path
        .to_str()
        .context("restricted receiver path is not valid UTF-8")?;
    if value.is_empty()
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'/' | b'.' | b'_' | b'-'))
    {
        bail!("restricted receiver path contains shell-sensitive characters");
    }
    Ok(value.to_owned())
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AuthorizedKeysChange {
    Unchanged,
    Installed,
    Revoked,
}

/// Add one managed entry without replacing an existing entry or touching
/// unrelated authorized_keys contents.
pub fn install_authorized_key(
    original: &[u8],
    entry: &AuthorizedKeyEntry,
) -> Result<(Vec<u8>, AuthorizedKeysChange)> {
    let marker = entry.marker();
    let mut exact = 0usize;
    let mut marker_collision = false;
    let mut key_collision = false;
    for line in original.split(|byte| *byte == b'\n') {
        if line == entry.line().as_bytes() {
            exact += 1;
            continue;
        }
        marker_collision |= last_ascii_token(line) == Some(marker.as_bytes());
        key_collision |= line_contains_transport_key(line, &entry.key);
    }
    if exact > 1 {
        bail!("authorized_keys contains duplicate entries for {}", marker);
    }
    if marker_collision {
        bail!(
            "authorized_keys already contains a different entry for {}",
            marker
        );
    }
    if key_collision {
        bail!("receiver transport key is already authorized by another authorized_keys line");
    }
    if exact == 1 {
        return Ok((original.to_vec(), AuthorizedKeysChange::Unchanged));
    }

    let mut updated = original.to_vec();
    if !updated.is_empty() && !updated.ends_with(b"\n") {
        updated.push(b'\n');
    }
    updated.extend_from_slice(entry.line().as_bytes());
    updated.push(b'\n');
    Ok((updated, AuthorizedKeysChange::Installed))
}

/// Remove exactly one managed entry.  A missing entry is an idempotent
/// no-op; collisions and duplicates fail instead of guessing which
/// authorization to retain.
pub fn revoke_authorized_key(
    original: &[u8],
    entry: &AuthorizedKeyEntry,
) -> Result<(Vec<u8>, AuthorizedKeysChange)> {
    let marker = entry.marker();
    let mut found = 0usize;
    let mut marker_collision = false;
    let mut key_collision = false;
    let mut updated = Vec::with_capacity(original.len());
    for line in original.split_inclusive(|byte| *byte == b'\n') {
        let without_newline = line.strip_suffix(b"\n").unwrap_or(line);
        if without_newline == entry.line().as_bytes() {
            found += 1;
        } else if last_ascii_token(without_newline) == Some(marker.as_bytes()) {
            marker_collision = true;
            updated.extend_from_slice(line);
        } else {
            key_collision |= line_contains_transport_key(without_newline, &entry.key);
            updated.extend_from_slice(line);
        }
    }
    if found > 1 {
        bail!("authorized_keys contains duplicate entries for {}", marker);
    }
    if marker_collision {
        bail!(
            "authorized_keys contains a different entry for {}; refusing revocation",
            marker
        );
    }
    if key_collision {
        bail!(
            "receiver transport key is also authorized by another authorized_keys line; refusing revocation"
        );
    }
    Ok((
        if found == 0 {
            original.to_vec()
        } else {
            updated
        },
        if found == 0 {
            AuthorizedKeysChange::Unchanged
        } else {
            AuthorizedKeysChange::Revoked
        },
    ))
}

fn last_ascii_token(line: &[u8]) -> Option<&[u8]> {
    line.rsplit(|byte| byte.is_ascii_whitespace())
        .find(|word| !word.is_empty())
}

fn line_contains_transport_key(line: &[u8], key: &TransportPublicKey) -> bool {
    let mut words = line
        .split(|byte| byte.is_ascii_whitespace())
        .filter(|word| !word.is_empty());
    let algorithm = key.algorithm.as_bytes();
    let blob = key.blob.as_bytes();
    while let Some(word) = words.next() {
        if word == algorithm && words.next() == Some(blob) {
            return true;
        }
    }
    false
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SshEndpoint(String);

impl SshEndpoint {
    /// Parse the deliberately narrow endpoint syntax accepted by automatic
    /// enrollment. Ports and unusual SSH routing belong in trusted ssh_config;
    /// accepting free-form destination text here would make OpenSSH's
    /// ProxyCommand expansion a shell-injection boundary.
    pub fn parse(value: &str) -> Result<Self> {
        let (user, host) = match value.split_once('@') {
            Some((user, host)) if !host.contains('@') => (Some(user), host),
            Some(_) => bail!("enrollment endpoint contains more than one @"),
            None => (None, value),
        };
        if user.is_some_and(|user| !safe_ssh_name(user)) || !safe_ssh_name(host) {
            bail!(
                "enrollment endpoint must be [user@]host using only letters, digits, dot, underscore, and hyphen"
            );
        }
        if host == "none" {
            bail!("none is not an enrollment host");
        }
        Ok(Self(value.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

fn safe_ssh_name(value: &str) -> bool {
    !value.is_empty()
        && !value.starts_with('-')
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EnrollmentRemoteCommand(String);

impl EnrollmentRemoteCommand {
    /// Construct shell source only from a validated absolute program and
    /// individually quoted arguments. sshd always invokes remote commands via
    /// the account's shell, even when the local process supplied one argv.
    pub fn new(program: &Path, args: &[String]) -> Result<Self> {
        let program = safe_receiver_path(program)?;
        if args.iter().any(|arg| arg.bytes().any(|byte| byte == 0)) {
            bail!("enrollment command argument contains NUL");
        }
        let mut words = Vec::with_capacity(args.len() + 1);
        words.push(program);
        words.extend(args.iter().cloned());
        Ok(Self(shell_words::join(words)))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EnrollmentRoute<'a> {
    Direct,
    ProxyJump { jump: &'a SshEndpoint },
}

/// Arguments for the trusted local OpenSSH client that enrolls HostB.  A jump
/// host receives only an opaque TCP stream; it never receives an agent socket
/// or an authenticated HostB session.
pub fn enrollment_ssh_args(
    target: &SshEndpoint,
    route: EnrollmentRoute<'_>,
    remote_command: &EnrollmentRemoteCommand,
) -> Vec<String> {
    let mut args = vec![
        "-a".to_owned(),
        "-x".to_owned(),
        "-k".to_owned(),
        "-T".to_owned(),
        "-o".to_owned(),
        "ClearAllForwardings=yes".to_owned(),
        "-o".to_owned(),
        "ControlMaster=no".to_owned(),
        "-o".to_owned(),
        "ControlPath=none".to_owned(),
        "-o".to_owned(),
        "ForwardX11=no".to_owned(),
        "-o".to_owned(),
        "PermitLocalCommand=no".to_owned(),
    ];
    match route {
        EnrollmentRoute::Direct => {
            // A route called direct must not inherit an implicit jump or proxy
            // from ssh_config.
            args.extend([
                "-o".to_owned(),
                "ProxyJump=none".to_owned(),
                "-o".to_owned(),
                "ProxyCommand=none".to_owned(),
            ]);
        }
        EnrollmentRoute::ProxyJump { jump } => {
            // -J does not apply destination command-line safety options to its
            // implicit jump process. A fixed ProxyCommand lets us constrain that
            // process explicitly while the inner SSH connection remains local and
            // end-to-end with HostB.
            args.push("-o".to_owned());
            args.push(format!(
                "ProxyCommand=ssh -a -x -k -T -o ClearAllForwardings=yes -o ControlMaster=no -o ControlPath=none -o ForwardX11=no -o PermitLocalCommand=no -W '[%h]:%p' -- {}",
                jump.as_str()
            ));
        }
    }
    args.push("--".to_owned());
    args.push(target.as_str().to_owned());
    args.push(remote_command.as_str().to_owned());
    args
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key() -> TransportPublicKey {
        let mut blob = Vec::new();
        for value in [ED25519_ALGORITHM.as_bytes(), &[7u8; ED25519_KEY_BYTES]] {
            blob.extend_from_slice(&(value.len() as u32).to_be_bytes());
            blob.extend_from_slice(value);
        }
        TransportPublicKey::parse(&format!(
            "{ED25519_ALGORITHM} {} ignored-comment",
            base64::engine::general_purpose::STANDARD.encode(blob)
        ))
        .unwrap()
    }

    fn id() -> EnrollmentId {
        EnrollmentId::parse("00112233445566778899aabbccddeeff").unwrap()
    }

    #[test]
    fn enrollment_ids_are_rfc_4122_uuids() {
        let generated = EnrollmentId::random();
        assert_eq!(generated.as_str().as_bytes()[12], b'4');
        assert!(matches!(generated.as_str().as_bytes()[16], b'8'..=b'9' | b'a'..=b'b'));
        assert!(EnrollmentId::parse("00112233445566770899aabbccddeeff").is_err());
        assert!(EnrollmentId::parse("00112233445566774899aabbccddeeff").is_err());
    }

    #[test]
    fn entry_is_a_fixed_restricted_command() {
        let entry = AuthorizedKeyEntry::new(
            id(),
            Path::new("/home/backup/.local/libexec/syq-receiver"),
            &key(),
        )
        .unwrap();
        assert!(entry.line().starts_with(
            "restrict,command=\"/home/backup/.local/libexec/syq-receiver --restricted-receiver --enrollment=00112233445566778899aabbccddeeff\" ssh-ed25519 "
        ));
        assert!(entry
            .line()
            .ends_with(" syq-enrollment:00112233445566778899aabbccddeeff"));
    }

    #[test]
    fn entry_rejects_shell_sensitive_receiver_paths() {
        let error = AuthorizedKeyEntry::new(id(), Path::new("/home/backup/bad path/syq"), &key())
            .unwrap_err();
        assert!(error.to_string().contains("shell-sensitive"));
    }

    #[test]
    fn transport_key_parser_checks_the_wire_blob() {
        let mut bad = Vec::new();
        bad.extend_from_slice(&11u32.to_be_bytes());
        bad.extend_from_slice(b"ssh-ed25519");
        bad.extend_from_slice(&31u32.to_be_bytes());
        bad.extend_from_slice(&[0u8; 31]);
        let error = TransportPublicKey::parse(&format!(
            "ssh-ed25519 {}",
            base64::engine::general_purpose::STANDARD.encode(bad)
        ))
        .unwrap_err();
        assert!(error.to_string().contains("wrong Ed25519 key length"));
    }

    #[test]
    fn install_is_idempotent_and_preserves_unrelated_lines() {
        let entry = AuthorizedKeyEntry::new(id(), Path::new("/opt/syq/receiver"), &key()).unwrap();
        let original = b"# administrator \xff comment\nssh-ed25519 AAAA existing\n";
        let (installed, change) = install_authorized_key(original, &entry).unwrap();
        assert_eq!(change, AuthorizedKeysChange::Installed);
        assert!(installed.starts_with(original));
        let (again, change) = install_authorized_key(&installed, &entry).unwrap();
        assert_eq!(change, AuthorizedKeysChange::Unchanged);
        assert_eq!(again, installed);
    }

    #[test]
    fn install_refuses_to_replace_a_conflicting_managed_entry() {
        let entry = AuthorizedKeyEntry::new(id(), Path::new("/opt/syq/receiver"), &key()).unwrap();
        let original = format!(
            "restrict,command=\"evil\" ssh-ed25519 AAAA {}\n",
            id().marker()
        );
        assert!(install_authorized_key(original.as_bytes(), &entry)
            .unwrap_err()
            .to_string()
            .contains("different entry"));
    }

    #[test]
    fn install_and_revoke_refuse_any_other_authorization_for_the_transport_key() {
        let transport = key();
        let entry =
            AuthorizedKeyEntry::new(id(), Path::new("/opt/syq/receiver"), &transport).unwrap();
        let unrestricted = format!(
            "{} {} administrator-key\n",
            transport.algorithm, transport.blob
        );
        assert!(install_authorized_key(unrestricted.as_bytes(), &entry)
            .unwrap_err()
            .to_string()
            .contains("already authorized"));

        let other_id =
            EnrollmentId::parse("10112233445546778899aabbccddeeff").expect("second UUID");
        let other =
            AuthorizedKeyEntry::new(other_id, Path::new("/opt/syq/other-receiver"), &transport)
                .unwrap();
        assert!(
            install_authorized_key(format!("{}\n", other.line()).as_bytes(), &entry)
                .unwrap_err()
                .to_string()
                .contains("already authorized")
        );

        let duplicate_authority = format!("{}\n{unrestricted}", entry.line());
        assert!(
            revoke_authorized_key(duplicate_authority.as_bytes(), &entry)
                .unwrap_err()
                .to_string()
                .contains("also authorized")
        );
    }

    #[test]
    fn revoke_removes_only_the_exact_managed_line() {
        let entry = AuthorizedKeyEntry::new(id(), Path::new("/opt/syq/receiver"), &key()).unwrap();
        let original = format!("before\n{}\nafter\n", entry.line());
        let (updated, change) = revoke_authorized_key(original.as_bytes(), &entry).unwrap();
        assert_eq!(change, AuthorizedKeysChange::Revoked);
        assert_eq!(updated, b"before\nafter\n");
    }

    #[test]
    fn revoke_refuses_a_marker_collision() {
        let entry = AuthorizedKeyEntry::new(id(), Path::new("/opt/syq/receiver"), &key()).unwrap();
        let original = format!("ssh-ed25519 AAAA administrator-key {}\n", entry.marker());
        assert!(revoke_authorized_key(original.as_bytes(), &entry)
            .unwrap_err()
            .to_string()
            .contains("different entry"));
    }

    #[test]
    fn endpoint_rejects_proxy_shell_syntax_and_multi_hop_forms() {
        for unsafe_endpoint in [
            "none",
            "user;touch@host",
            "user@host,other",
            "user@$(command)",
            "-option",
            "user name@host",
            "user@@host",
        ] {
            assert!(
                SshEndpoint::parse(unsafe_endpoint).is_err(),
                "accepted {unsafe_endpoint}"
            );
        }
        assert_eq!(
            SshEndpoint::parse("backup_user@host-b.example")
                .unwrap()
                .as_str(),
            "backup_user@host-b.example"
        );
    }

    #[test]
    fn remote_command_quotes_every_argument_for_the_remote_shell() {
        let command = EnrollmentRemoteCommand::new(
            Path::new("/opt/syq/receiver"),
            &["enroll".into(), "argument with spaces;$(bad)".into()],
        )
        .unwrap();
        assert_eq!(
            command.as_str(),
            "/opt/syq/receiver enroll 'argument with spaces;$(bad)'"
        );
    }

    #[test]
    fn proxyjump_route_keeps_authentication_local() {
        let target = SshEndpoint::parse("backup@hostB").unwrap();
        let jump = SshEndpoint::parse("user@hostA").unwrap();
        let command = EnrollmentRemoteCommand::new(Path::new("/opt/syq/enroll"), &[]).unwrap();
        assert_eq!(
            enrollment_ssh_args(&target, EnrollmentRoute::ProxyJump { jump: &jump }, &command),
            [
                "-a",
                "-x",
                "-k",
                "-T",
                "-o",
                "ClearAllForwardings=yes",
                "-o",
                "ControlMaster=no",
                "-o",
                "ControlPath=none",
                "-o",
                "ForwardX11=no",
                "-o",
                "PermitLocalCommand=no",
                "-o",
                "ProxyCommand=ssh -a -x -k -T -o ClearAllForwardings=yes -o ControlMaster=no -o ControlPath=none -o ForwardX11=no -o PermitLocalCommand=no -W '[%h]:%p' -- user@hostA",
                "--",
                "backup@hostB",
                "/opt/syq/enroll",
            ]
        );
    }

    #[test]
    fn direct_route_disables_implicit_ssh_config_proxies() {
        let target = SshEndpoint::parse("backup@hostB").unwrap();
        let command = EnrollmentRemoteCommand::new(Path::new("/opt/syq/enroll"), &[]).unwrap();
        let args = enrollment_ssh_args(&target, EnrollmentRoute::Direct, &command);
        assert!(args.windows(2).any(|args| args == ["-o", "ProxyJump=none"]));
        assert!(args
            .windows(2)
            .any(|args| args == ["-o", "ProxyCommand=none"]));
        assert_eq!(
            &args[args.len() - 3..],
            ["--", "backup@hostB", "/opt/syq/enroll"]
        );
    }
}
